Update reqLog.txt
ran the auth in thunderclient a few times while experimenting with why it may be throwing the following error:
Error: secretOrPrivateKey must have a value
    at module.exports [as sign] (C:\Users\DKitc\Documents\GitHub\node-js-tutorial\tutorial-part12\node_modules\jsonwebtoken\sign.js:107:20)
    at handleLogin (C:\Users\DKitc\Documents\GitHub\node-js-tutorial\tutorial-part12\controllers\authController.js:27:29)

Unable to find error in the code, returned experimented lines to original. Will need to continue to work on this tomorrow